#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

restore0Dir
for region in $(foamListRegions)
do
    runApplication -s $region changeDictionary \
        -region $region -subDict dictionaryReplacement
done

runApplication -s air topoSet -region air
runApplication -s air setFields -region air

\foamToVTK -cellZone tree_cube_1
runApplication $(getApplication)

#------------------------------------------------------------------------------
